Upgrading ldapjs version
jsumners/adldap pull request #2
Opened 2017-07-18 21:43 UTC by ihavenoidea14

I'm new at this, so if I need to make any changes I'd be happy to.

2017-07-18 22:18 UTC, jsumners requested changes

2017-07-18 22:18 UTC, jsumners commented on package.json
> +    "eslint-plugin-import": "^2.7.0",
These dependencies are unnecessary. Please remove them.

2017-07-18 22:18 UTC, jsumners commented on package.json
> +  "version": "3.1.3",
Please do not update the version. That is for release maintainers (i.e. me) to do.

2017-07-18 22:18 UTC, jsumners commented on package-lock.json
> +{
Please remove this `package-lock.json` file.

2017-07-18 23:34 UTC, ihavenoidea14 commented
Ok, sorry for the sloppiness. Great module by the way, very useful.

2017-07-19 12:27 UTC, jsumners approved these changes

2017-07-19 12:28 UTC, jsumners commented
No problem. Corrections are easy to make. Thank you for the PR.

2017-07-19 12:28 UTC, merged